# 5 NumPy Operations I bet, you don't know!
##### Author: [Tushar Nankani](https://www.linkedin.com/in/tusharnankani/)

### *This Jupyter Notebook will take you to through 5 NumPy operations, with explainations and examples.*

One of the main benefits is its **extensive set of libraries**, **a collection of routines and functions** that help data scientists perform complex tasks quite *effortlessly* without writing a single line of code. 
- One such important function is numerical Python aka **NumPy** which is a fundamental library, well known for *high-performance multi-dimensional array* and can be used for different mathematical functions like linear algebra, Fourier Transformations, etc. as well as logical operations.

###### *This Jupyter Notebook will take you to through 5 NumPy operations, with explainations and examples.*

- [np.where](http://localhost:8888/notebooks/Desktop/Jovian.ml/TUSHAR/numpy-assignment/numpy-array-operations.ipynb#Function-1---np.where)
- [np.unravel_index](http://localhost:8888/notebooks/Desktop/Jovian.ml/TUSHAR/numpy-assignment/numpy-array-operations.ipynb#Function-2---np.unravel_index)
- [np.random](http://localhost:8888/notebooks/Desktop/Jovian.ml/TUSHAR/numpy-assignment/numpy-array-operations.ipynb#Function-3---np.random)
- [np.diag](http://localhost:8888/notebooks/Desktop/Jovian.ml/TUSHAR/numpy-assignment/numpy-array-operations.ipynb#Function-4---np.diag())
- [np.pad](http://localhost:8888/notebooks/Desktop/Jovian.ml/TUSHAR/numpy-assignment/numpy-array-operations.ipynb#Function-5---np.pad)



Let's begin by **importing Numpy** and *listing out the functions covered in this notebook*.

In [1]:
import numpy as np

## List of functions explained 
```python
function1 = np.where(condition, [x, y])
function2 = np.unravel_index(indices, shape, order='C') 
function3 = np.random.randint(low, high=None, size=None, dtype='l')
function4 = np.diag(array, k=0)
function5 = np.pad(array, pad_width, mode='constant', **kwargs)
```

# Function 1 - `np.where`

-  np.where() is an inbuilt function that **returns the indices of elements** in an input array where the given condition is satisfied.
-  If you want to find the index in Numpy array, then you can use the **np.where()** function.

```python
np.where(condition, [x, y])
```

- Return elements chosen from `x` or `y` depending on `condition`.


### Parameters
- condition : array_like, bool
    - Where True, yield `x`, otherwise yield `y`.
- x, y : array_like
    - Values from which to choose. `x`, `y` and `condition` need to be broadcastable to some shape.

### Returns
- out : ndarray
    - An array with elements from `x` where `condition` is True, and elements from `y` elsewhere.

In [2]:
# Example

# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

np.where(arr == 19)

(array([8], dtype=int64),)

- **The result is a tuple of arrays (one for each axis) containing the indices where value 19 exists in the array.**
- Tuple of arrays returned :  `(array([8], dtype=int64),)`
- Elements with value 19 exists at following indices: `[8]`

In [3]:
# Example 
arr = np.array([11, 19, 13, 14, 15, 11, 19, 21, 19, 20, 21])

# Prints all indices where 19 is present;
print(np.where(arr == 19)[0])

# prints the first occurence of 19;
print(np.where(arr == 19)[0][0])

[1 6 8]
1


- ***Indexing*** will help to find various occurences of the the element we are looking at;

In [4]:
# Using some condtion:
arr = np.array([11, 19, 18, 14, 15, 11, 19, 21, 46, 29, 21, 19])

np.where((arr > 15) & (arr < 21))


(array([ 1,  2,  6, 11], dtype=int64),)

- In the above example, it will return the element values, which are less than 21 and more than 14.

In [5]:
# Example
np.where(arr == 100)[0][0]

IndexError: index 0 is out of bounds for axis 0 with size 0

- If the element is not present, it returns an empty array;
- Hence, we could avoid indexing and directly print the array.

In [6]:
# For a 2D array;
vec = np.array([[8, 2, 3], 
                [4, 5, 8], 
                [7, 8, 9]])

np.where(vec == 8)

(array([0, 1, 2], dtype=int64), array([0, 2, 1], dtype=int64))

- This returns a *different tuple* for every **different axis**;

#### The best way to view them:

In [7]:
result = np.where(vec == 8)

listOfIndices = list(zip(result[0], result[1]))

print(listOfIndices)

for indice in listOfIndices:
    print(indice)

[(0, 0), (1, 2), (2, 1)]
(0, 0)
(1, 2)
(2, 1)


##### Some closing comments:
- If you want to find the index of the value in Python numpy array, then **np.where().**

# Function 2 - `np.unravel_index`

- Converts a flat index or array of flat indices into a tuple of coordinate arrays.

```python
np.unravel_index(indices, shape, order='C')
```

#### Parameters

- indices : array_like
    - An integer array whose elements are indices into the flattened version of an array of dimensions ``shape``. 
    
- shape : tuple of ints
    - The shape of the array to use for unraveling ``indices``.

- order : {'C', 'F'}, optional
    - Determines whether the indices should be viewed as indexing in 
        - row-major (C-style) or;
        - column-major (Fortran-style) order.
        
#### Returns

- unraveled_coords : tuple of ndarray
    - Each array in the tuple has the same shape as the ``indices`` array.




### Consider a (6,7,8) shape array!

In [8]:
arr = np.random.random((6, 7, 8))

###  Now, what is the index (x,y,z) of the 100th element?

#### Now the *naive approach* would be :
- If a 3D matrix of size (6, 7, 8) is given, it would consist of 336 (6 * 7 * 8) elements;
- so if we would want to find the **100th element**;
- we could reshape it to 1D array, and find the element at the **99th index**;
- for reshape we would have to do: `arr.reshape(336)`
- **IMP: but we could also do: `arr.reshape(-1)`**
    - this would covert any matrix shape, into a 1D array;
- Then, we could use, `np.where(arr == 100th element)`

In [9]:
# Naive approach
np.where(arr == arr.reshape(-1)[99])

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

##### Hence, the answer is: (1, 5, 3), but there's a better method;

In [10]:
# Example 1 - working
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

### This *directly* gives the ***index of any element***, *without having to create an array*.

In [11]:
# Example 2 - working
np.unravel_index([22, 41, 37], (7, 6), order = 'F') 

(array([1, 6, 2], dtype=int64), array([3, 5, 5], dtype=int64))

##### F stands for column-major (Fortran-style) order.
- so, this gives:
    - 22nd index - (1, 3)
    - 41nd index - (6, 5)
    - 37nd index - (2, 5)

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
np.unravel_index(4, (2, 2))

ValueError: index 4 is out of bounds for array with size 4

- This precisely breaks because, there are only 4 elements (*indexed from 0 to 3*), hence 4th element doesn't exist;
- This could be avoided if we made sure that the **index** we are passing is *strictly less than*the **the size of the matrix**..!!

##### Some closing comments:
- If you want to find the indices of specific elements, Column/Row wise, this function would be *very very helpful*!!

# Function 3 - `np.random`
###### This property has a lot of methods and I wanted to differentiate between them and let everyone know the **difference.**

```python
np.random.random((size=None))
# Return random floats in the half-open interval [0.0, 1.0).


np.rand(d0, d1, ..., dn)
# Random values in a given shape.


np.random.randn(d0, d1, ..., dn)
# Return a sample (or samples) from the "standard normal" distribution.


np.random.randint(low, high=None, size=None, dtype='l')
# Return random integers from `low` (inclusive) to `high` (exclusive).
```

In [13]:
# Examples:
# Note the parentheses in all; 

arr1 = np.random.random((5, 3))    # returns a random array of size (5, 3) in the half-open interval [0.0, 1.0)
arr1

array([[0.50568307, 0.66985235, 0.4496273 ],
       [0.61531243, 0.50183194, 0.31340942],
       [0.95830044, 0.42809031, 0.46162155],
       [0.03345813, 0.04953914, 0.23415557],
       [0.35477876, 0.75716488, 0.16918824]])

In [14]:
arr2 = np.random.rand(5, 3)        # returns a random array of size (5, 3)
arr2

array([[0.57565793, 0.1357972 , 0.62321899],
       [0.51946086, 0.40555523, 0.39768904],
       [0.42194992, 0.16020807, 0.90767351],
       [0.75323901, 0.01822832, 0.05601656],
       [0.02612274, 0.02692122, 0.63364275]])

In [15]:
arr3 = np.random.randn(5, 3)       # returns a random array of size (5, 3) from the "standard normal" distribution; it also includes negative values.
arr3

array([[ 1.36546995, -0.56689423, -0.78161556],
       [ 2.10261382, -0.4199759 , -1.60504606],
       [ 1.98128005,  0.05132418, -1.08060803],
       [ 0.2488728 , -1.27827401, -1.49154348],
       [-0.81413264,  0.7355861 , -0.04819203]])

In [16]:
arr4 = np.random.randint(5, 10)    # returns a random array of default size 1, between [5, 10)
arr4

7

In [17]:
arr5 = np.random.randint(5, 10, (5, 3)) # returns a random array of size (5, 3), values between [5, 10)
arr5

array([[8, 5, 8],
       [8, 9, 7],
       [7, 6, 9],
       [7, 5, 6],
       [6, 7, 5]])

In [18]:
# Example - breaking (to illustrate when it breaks)
# NOTE: THESE METHODS DON'T USUALLY BREAK; THEY WORK FOR EVERY POSSIBLE INPUT;
# Just the parentheses are TO BE KEPT IN MIND;
np.random.random(5, 3)

TypeError: random() takes at most 1 positional argument (2 given)

##### NOTE: THESE METHODS DON'T USUALLY BREAK; THEY WORK FOR EVERY POSSIBLE INPUT;
###### Just the parentheses are TO BE KEPT IN MIND;
- Since, a single argument: **shape** is to be passed, hence the input should have been `(5, 3)` instead of `5, 3`!

##### Some closing comments:
- these methods help a lot for testing purposes;
- they also help in generating random raw data;
- everyone should know the difference between all of them!

## Function 4 - `np.diag()`

- diag represents diagonal;

```python
np.diag(v, k=0)
'''
# Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.
'''
# Extract a diagonal or construct a diagonal array.
```

In [19]:
# Example 1 - working
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])
np.diag(arr1)    # extracting a diagonal from a defined array;

array([1, 5, 9])

In [20]:
arr2 = np.eye(5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# Example 2 - working;
np.diag(arr2, k = -1)

array([0., 0., 0., 0.])

#### k : int, optional
 
- The default is 0. Use **`k>0`** for diagonals *above the main diagonal*, and **`k<0`** for diagonals *below the main diagonal*

###### Printing a 5x5 matrix with values 1,2,3,4 just above the diagonal, 

In [22]:
# Example 2.1 - working 
np.diag(np.arange(1, 5), k = 2)
# dynamically changing size of the matrix;

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
np.diag()

TypeError: _diag_dispatcher() missing 1 required positional argument: 'v'

1 required positional argument: array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal. 

##### Some closing comments:
- `np.diag()` is very helpful in **matrix manipulations and calculations** related to the diagonal..!!

## Function 5 - `np.pad`

Signature: np.pad(array, pad_width, mode='constant', **kwargs)
Docstring:
Pad an array.

Parameters
----------
- array : array_like of rank N
    - The array to pad.
- pad_width : {sequence, array_like, int}
- mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the median value of all or part of the
        vector along each axis.
    'minimum'
        Pads with the minimum value of all or part of the
        vector along each axis.
    'symmetric'
        Pads with the reflection of the vector mirrored
        along the edge of the array.
    'wrap'
        Pads with the wrap of the vector along the axis.
        The first values are used to pad the end and the
        end values are used to pad the beginning.
    'empty'
        Pads with undefined values.
        
Returns
-------
pad : ndarray
    Padded array of rank equal to `array` with shape increased
    according to `pad_width`.


#### Assume a random array of shape (5, 5)

### Now, how would you add a border (filled with 0's) around it?

##### The NAIVE APPROACH would be hardcore indexing!

In [24]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# NAIVE APPROACH - using indexing;
arr[0], arr[-1] = 0, 0
arr[:, 0:1], arr[:, -1] = 0, 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
# Example 1 - working
arr = np.ones((3, 3))
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### NOTE: It adds padding to exisiting array; and doesn't edit the array!

In [27]:
# Example 2 - working
arr = np.random.rand(3, 3)
np.pad(arr, pad_width=1, mode='mean')

array([[0.36731388, 0.47420486, 0.34393646, 0.28380033, 0.36731388],
       [0.35776669, 0.32174829, 0.73107248, 0.02047931, 0.35776669],
       [0.51370908, 0.61182062, 0.27853117, 0.65077545, 0.51370908],
       [0.23046586, 0.48904565, 0.02220572, 0.18014621, 0.23046586],
       [0.36731388, 0.47420486, 0.34393646, 0.28380033, 0.36731388]])

- There are **various modes**, with which we could pad the array with!

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
np.pad(arr, mode = "minimum")

TypeError: _pad_dispatcher() missing 1 required positional argument: 'pad_width'

- Why it breaks: This usually breaks if it has missing position arguments: `array` and `pad_width` are **required positional arguments.**

##### Some closing comments:
- `np.pad()` is very helpful in **creating excess pseudo data**, which needs to be manipulated.
- It has many, many modes which makes it very, very useful..!! 

## Conclusion

### *List of functions explained:*
```python
function1 = np.where(condition, [x, y])
function2 = np.unravel_index(indices, shape, order='C') 
function3 = np.random.randint(low, high=None, size=None, dtype='l')
function4 = np.diag(array, k=0)
function5 = np.pad(array, pad_width, mode='constant', **kwargs)
```

- **NumPy** has a whole lot of functions and methods, but it is impossible to know everything!
- I hope, you learnt a lot, these functions are very useful! 
- The best way to *learn* it and get hang of it by *playing* along with it, in this Jupyter Notebook Playground!
- As they say:
    - ***A good programmer is a good googler!***
        - so all you need to know is, how to *google* your required needs!
            - so that your needs are fulfilled!
            
###### Thank you
- [Tushar Nankani](https://github.com/tusharnankani)

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
- Official tutorial: https://numpy.org/devdocs/user/quickstart.html
- Numpy tutorial on W3Schools: https://www.w3schools.com/python/numpy_intro.asp
- Advanced Numpy (exploring the internals): http://scipy-lectures.org/advanced/advanced_numpy/index.html
* Extra Help : https://appdividend.com/