# Numerical Computing with Python and Numpy

### Working with numerical data

- The "data" in Data Analysis typically refers to numerical data e.g. stock prices, sales figures, sensor measurements, sports scores, database tables etc. 
- The [Numpy library](https://numpy.org/) provides specialized data structures, functions and other tools for numerical computing in Python. Let's work through an example to see why & how to use Numpy for working with numerical data.

> Let's say we want to use climate data like the temperature, rainfall and humidity in a region to determine if the region is well suited for growing apples. A really simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Farenheit), rainfall (in  millimeters) & average relative humidity (in percentage) as a linear equation.
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

We're expressing the yield of apples as a weighted sum of the temperature, rainfall and humidity. Obviously, this is an approximation, since the actual relation may not necessarily be linear. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might we able to come up with reasonable values for the weights `w1`, `w2` and `w3`. Here's an example set of values:

In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

https://i.imgur.com/TXPBiqv.png

Given some climate data for a region, we can now predict what the yield of apples in the region might look like. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record the climate data for a region.

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [4]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


> To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector i.e. a list of numbers.

In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

> The three numbers in each vector represent the temperature, rainfall and humidity data respecively. The set of weights to be used in the forumla can also be represented as a vector.

In [6]:
weights = [w1, w2, w3]

In [7]:
def crop_yield(region, weights):
    res = 0
    for x, y in zip(region, weights):
        res += x * y
    return res    

In [8]:
crop_yield(kanto, weights)

56.8

In [9]:
crop_yield(johto, weights)

76.9

# Going from Python lists to Numpy arrays


- The calculation performed by the `crop_yield` (element-wise multiplication of two vectors, and taking a sum of the results) is also called the *dot product* of the two vectors. 
- Learn more about dot product here: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length

#### The Numpy library provides a built-in function to perform the dot product of two vectors. However, the lists must first be converted to numpy arrays before we can perform the operation. To begin, let's import the `numpy` module. It is common practice to import numpy with the alias `np`.

In [10]:
import numpy as np

> An array in numpy can be created using: np.array() function

In [11]:
kanto = [73, 67, 43]

In [12]:
kanto

[73, 67, 43]

In [13]:
type(kanto)

list

In [14]:
kanto = np.array([73, 67, 43])

In [15]:
kanto

array([73, 67, 43])

In [16]:
type(kanto)

numpy.ndarray

- identifying the difference between python lists and NumPy arrays

In [17]:
weights = np.array([w1, w2, w3])

In [18]:
weights

array([0.3, 0.2, 0.5])

In [19]:
weights[2]

0.5

- Just like lists, Numpy arrays support the indexing notation `[]`

# Operating on Numpy arrays

> We can now compute the dot product of the two vectors using the `np.dot` function

In [20]:
np.dot(kanto, weights)

56.8

In [21]:
'''
def crop_yield(region, weights):
    res = 0
    for x, y in zip(region, weights):
        res += x * y
    return res
'''
# the above peice of code can be simply replaced by `np.dot` function

'\ndef crop_yield(region, weights):\n    res = 0\n    for x, y in zip(region, weights):\n        res += x * y\n    return res\n'

In [22]:
temp = [1, 2, 3]

In [23]:
np.dot(kanto, temp)

336

### NumPy arrays are flexible, as seen above, a dot product can be taken with normal python list

In [24]:
var = [1, 2, 3]

In [25]:
np.dot(temp, var)

14

`np.dot(kanto, weights)` 
> the following piece of code can be written with low level operators:\
- We can achieve the same result with lower level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the sum of the resulting numbers.
- The `*` operator performs an element-wise multiplication of two arrays (assuming they have the same size), and the `sum` method calcuates the sum of numbers in an array.

In [26]:
(kanto * weights).sum()

56.8

In [27]:
np.dot(kanto, weights)

56.8

## Benefits of using Numpy arrays

There are a couple of important benefits of using Numpy arrays instead of Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise and intutive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yeild`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops which are interpreted at runtime

Here's a quick comparision of dot products done of vectors with a million elements each using Python loops vs. Numpy arrays.

In [28]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

> `%%time` is a magic command. It's a part of IPython.

- `%%time` prints the wall time for the entire cell whereas `%time` gives you the time for first line only.

- Read more about it in the [documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html?highlight=%25time#magic-time)

In [29]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

Wall time: 401 ms


833332333333500000

In [30]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 996 µs


-1942957984

### As you can see, using `np.dot` is 100 times faster than using a `for` loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

## Multi-dimensional Numpy arrays 

We can now go one step further, and represent the climate data for all the regions together using a single 2-dimensional Numpy array.

In [31]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [32]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [33]:
type(climate_data)

numpy.ndarray

If you've taken a linear algebra class in high school, you might recognize the above 2-d array as a *matrix* with 5 rows (one for each region) and 3 columns (containing values for temperature, rainfall and humidity).

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">

- Numpy arays can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

In [34]:
climate_data.shape

(5, 3)

##### NOTE: 
it is `climate_data.shape` and not `climate_data.shape()`

In [35]:
weights

array([0.3, 0.2, 0.5])

In [36]:
weights.shape

(3,)

#### *The best way to count shape manually: *
- enter the round brackets first, ([[],,,[]])
- count the number of elements --> this is the **first value** of .shape
- then enter the next layer, enter one of the square brackets
- then count the number of elements --> this is the **second value** of .shape
- and so on ...

In [37]:
temp = np.array([[1, 2, 3],
                 [3, 4, 5],
                 [6, 7, 8]])

In [38]:
temp

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
temp.shape

(3, 3)

In [40]:
# if
temp = np.array([[1, 2, 3],
                 [3, 4, 5],
                 [6, 7, 8, 9]])

In [41]:
temp

array([list([1, 2, 3]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [42]:
type(temp)

numpy.ndarray

In [43]:
temp.shape

(3,)

- *If temp has a mismatch of rows, the above answers can be seen^*

In [44]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [45]:
arr3.shape

(2, 2, 3)

### *The explaination of above*:
- enter the bracket ()
- count the number of elements: in this case 2
    - PS, it is called axis = 0
- then enter the next bracket [] (axis = 2): 
- count the number of elements: 2
- then enter the next bracket []: (axis = 3)
- count the number of elements: 3

In [46]:
arr3.dtype

dtype('float64')

##### Note: if one of the values of the np.array is float, the datatype becomes float

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5x3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

You can learn about matrices and matrix multiplication by watching the first 3-4 videos of this playlist: https://www.youtube.com/watch?v=xyAuNHPsq-g&list=PLFD0EB975BA0CC1E0&index=1

##### *We can use the `np.matmul` function from Numpy, or simply use the `@` operator to perform matrix multiplication.*

In [47]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [48]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

#### *Playing around with mat mul*
- note: `ar23` means a 2d matrix, with shape (2, 3)

In [49]:
ar32 = np.array([[1, 2], 
                [1, 2], 
                [1, 2]])

In [50]:
ar23 = np.array([[1, 2, 3], 
                [1, 2, 3]])

In [51]:
ar33 = np.array([[1, 2, 3], 
                [1, 2, 3], 
                [1, 2, 3]])

In [52]:
ar32 @ ar23 

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [53]:
ar23 @ ar32 

array([[ 6, 12],
       [ 6, 12]])

> `[p X q] @ [q X r]` leads to a matrix of: `[p X r]`
- Note: `q` should be equal in both the matrix

In [54]:
ar33 @ ar23

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt` which contains 10,000 climate data (temperature, rainfall & humidity) in the following format:


```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

This format of storing data is known as *comma separated values* or CSV. 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)




To read this file into a numpy array, we can use the `genfromtxt` function.

In [55]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1f291063888>)

In [56]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [57]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [59]:
climate_data.shape

(10000, 3)

We can now use a matrix mulplication operator `@` to predict the yield of apples for the entire dataset using a given set of weights.

In [60]:
weights = np.array([0.3, 0.2, 0.5])

In [61]:
climate_data @ weights

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [62]:
yields = climate_data @ weights

In [63]:
yields.shape

(10000,)

- We can now add the `yields` back to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [68]:
yields.reshape(10000, 1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [64]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [65]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [66]:
climate_results.shape

(10000, 4)

There are a couple of subtleties here:

* We need to provide to `axis` argument to `np.concatenate` to specify the dimension along with concatenation should be performed.

* The arrays being concatenated should have the same number of dimensions, and the same length along each dimension, except the one along which concatenation is being performed. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function here to change the shape of `yields` from `(10000,)` to `(10000,1)`.

Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

The best way to understand what an Numpy function does is to experiment with it and read the documentation using the `help` function to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

Let's write the final results from our computation above back to a file using the `np.savetxt` function.

In [70]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           header='temperature,rainfall,humidity,yield_apples', 
           comments='')

The results are written back in the CSV format to the file `climate_results.txt`. 

```
temperature,rainfall,humidity,yield_apples
25.00 76.00 99.00 72.20
39.00 65.00 70.00 59.70
59.00 45.00 77.00 65.20
84.00 63.00 38.00 56.80
66.00 50.00 52.00 55.80
41.00 94.00 77.00 69.60
91.00 57.00 96.00 86.70
49.00 96.00 99.00 83.40
67.00 20.00 28.00 38.10
...
```



##### Numpy provides hundreds of functions for peforming operations on arrays. Here are some common functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** Since Numpy offers hundreds of functions for operating on arrays, it can sometimes be hard to find exactly what you need. The easiest way to find the right function is to do a web search e.g. searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

## Arithmetic operations and broadcasting

Numpy arrays support arithmetic operators like `+`, `-`, `*` etc. You can perform an arithmetic operation with a single number (also called scalar), or with another array of the same shape. This makes it really easy to write mathemtical expressions with multi-dimensional arrays.

In [80]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [81]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [82]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [83]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [84]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [85]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [86]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

- Numpy arrays also support *brodcasting*, which allows arthmetic operations between two array having a different number of dimensions, but compatible shapes. Let's look at an example to see how it works.

In [87]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [88]:
arr2.shape

(3, 4)

In [89]:
arr4 = np.array([4, 5, 6, 7])

In [90]:
arr4.shape

(4,)

In [91]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

- this happens because, precisely, 
`[4, 5, 6, 7], 
 [4, 5, 6, 7], 
 [4, 5, 6, 7]]`
- this is created, it is called broad casting

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated 3 times to match the shape `(3, 4)` of `arr2`. This is pretty useful, because numpy performs the replication without actually creating 3 copies of the smaller dimension array.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [92]:
arr5 = np.array([7, 8])

In [93]:
arr5.shape

(2,)

In [94]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

- In the above example, even if `arr5` is replicated 3 times, it will not match the shape of `arr2`, hence `arr2 + arr5` cannot be evaluted successfully. Learn more about brodcasting here: https://numpy.org/doc/stable/user/basics.broadcasting.html

Numpy arrays also support comparision operations like `==`, `!=`, `>` etc. The result is an array of booleans.

In [97]:
arr1 = np.array([[1, 2, 3], 
                 [3, 4, 5]])
arr2 = np.array([[2, 2, 3], 
                 [1, 2, 5]])

In [98]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [99]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [100]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [101]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

- A common use case for this is to count the number of equal elements in two arrays using the `sum` method. Remember that `True` evalues to `1` and `False` evaluates to `0` when booleans are used in arithmetic operations.

In [102]:
(arr1 == arr2).sum()

3

## Array indexing and slicing

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in a fairly intuitive fashion. You can provide a comma separated list of indices or ranges to select a specific element or a subarray (also called slice) from a numpy array.

In [103]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [104]:
arr3.shape

(3, 2, 4)

In [105]:
# Single element
arr3[1, 1, 2]

36.0

In [106]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [107]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [108]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [109]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [110]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [111]:
# Using too many indices
arr3[1,3,2,1]

IndexError: too many indices for array

The notation and results can confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of a desired shape with fixed or random values. Check the out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more about the following functions.

In [112]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [113]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## NOTE: 
*silly mistakes*
- np.zeros **((** 3, 2 **))**
- np.ones **([** 3, 2 **])**

In [114]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
# Random vector
np.random.rand(5)

array([0.28982941, 0.03845   , 0.01669995, 0.69572734, 0.16474928])

In [116]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[-1.47425481,  0.27259317, -0.91787264],
       [ 0.50767288,  1.05648419,  0.36380515]])

## Docstring:
**np.random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the "standard normal" distribution.**

**np.random.rand(d0, d1, ..., dn)
Random values in a given shape.**

**Docstring:
np.random.random(size=None)
Return random floats in the half-open interval**

In [119]:
# Random vector
np.random.randn(5, 2)

array([[ 1.05517016, -1.25020719],
       [-1.24234391,  0.70733226],
       [-0.39080922, -0.53924278],
       [ 0.35669944, -1.87540576],
       [ 0.10498776,  0.54939912]])

In [120]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [121]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [123]:
# Range with start, end and step
np.arange(10, 90, 17)

array([10, 27, 44, 61, 78])

In [124]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [125]:
# Equally spaced numbers in a range
np.linspace(3, 27, 8)

array([ 3.        ,  6.42857143,  9.85714286, 13.28571429, 16.71428571,
       20.14285714, 23.57142857, 27.        ])

## Exercises and Further Reading

Try the following exercises to become familiar with Numpy and practice your skills:

- Assignment on Numpy array functions: https://jovian.ml/aakashns/numpy-array-operations
- (Optional) 100 numpy exercises: https://jovian.ml/aakashns/100-numpy-exercises

We've covered the following topics in this tutorial:

- Going from Python lists to Numpy arrays
- Operating on Numpy arrays
- Benefits of using Numpy arrays over lists
- Multi-dimensional Numpy arrays
- Working with CSV data files
- Arithmetic operations and broadcasting
- Array indexing and slicing
- Other ways of creating Numpy arrays


Check out the following resouces for learning more about Numpy:

- Official tutorial: https://numpy.org/devdocs/user/quickstart.html
- Numpy tutorial on W3Schools: https://www.w3schools.com/python/numpy_intro.asp
- Advanced Numpy (exploring the internals): http://scipy-lectures.org/advanced/advanced_numpy/index.html