# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


### Solutions by [Tushar Nankani](https://github.com/tusharnankani)

Will be using Unicode characters for wrong and correct answers:
- ☑ `&#x2611;` or `&#9745;`

- ☒ `&#x2612;` or `&#9746;`

#### 1. Import the numpy package under the name `np` (★☆☆)  
&#x2611;

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
&#x2612;

```python
print(np.__version__)
np.show_config()
```

#### 3. Create a null vector of size 10 (★☆☆)
&#x2611;

In [2]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
&#x2612;

In [3]:
# hint: size, itemsize
print(vec.size * vec.itemsize, "bytes")

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
&#x2612;

```python
%run `python -c "import numpy; numpy.info(numpy.add)"`
```

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
&#x2611;

In [4]:
not_so_null = np.zeros(10)
not_so_null[4] = 1
not_so_null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
&#x2611;

In [5]:
%%time
v = np.array(list(range(10, 50)))
v

Wall time: 0 ns


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
%%time
v = np.arange(10, 50)
v

Wall time: 0 ns


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
&#x2611;

In [7]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
&#x2611;

In [8]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
&#x2612;

In [9]:
# NOTE: np.nonzero
d = np.nonzero([1,2,0,0,4,0])
d

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
&#x2611;

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)
&#x2611;

In [11]:
np.random.randn(3, 3, 3)

array([[[-1.5392934 , -0.02175218,  0.34069457],
        [-1.41517197, -2.5244337 ,  0.44568167],
        [ 0.34993104,  0.64319678,  2.41978765]],

       [[-0.32320434, -0.05817988, -0.59578328],
        [ 1.02475181, -0.76943826, -0.26669537],
        [ 0.66001175, -1.0106909 , -2.1992011 ]],

       [[-0.28851923,  1.12576443, -0.41912693],
        [ 2.00270768,  0.11833054,  0.19874244],
        [-1.53042339,  0.48659421,  0.21094708]]])

In [12]:
np.random.rand(3, 3, 3)

array([[[6.81293783e-01, 5.85420731e-01, 5.66687983e-01],
        [8.92292225e-01, 8.16010154e-01, 9.83210362e-01],
        [1.60105643e-01, 8.77111561e-02, 6.71175621e-01]],

       [[4.87309718e-01, 2.23399695e-01, 9.47873010e-01],
        [4.02323380e-01, 8.96868116e-01, 1.78477733e-01],
        [8.96988287e-01, 4.90571429e-01, 1.25673597e-01]],

       [[4.00552991e-01, 2.91247703e-04, 3.43262463e-01],
        [5.96191902e-01, 5.10033910e-01, 3.97762109e-01],
        [9.10100343e-01, 9.58790004e-01, 1.30293966e-01]]])

In [13]:
np.random.random((3, 3, 3))

array([[[0.7660217 , 0.21935208, 0.36753442],
        [0.09047999, 0.42603556, 0.58377883],
        [0.12724039, 0.73023941, 0.07891678]],

       [[0.57468846, 0.31240196, 0.99687039],
        [0.3050296 , 0.23092563, 0.67405827],
        [0.45975778, 0.69257293, 0.97177991]],

       [[0.27093919, 0.00470172, 0.50234387],
        [0.16902863, 0.45228077, 0.84469697],
        [0.84319189, 0.33617083, 0.89143131]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
&#x2611;

In [14]:
np.random.random((10, 10)).max()

0.9967818500910212

In [15]:
np.random.random((10, 10)).min()

0.004539842620549739

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
&#x2611;

In [16]:
np.random.random(30).mean()

0.3904102220936308

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
&#x2612;

In [17]:
ans = np.ones([5, 5])
ans[1:-1, 1:-1] = 0  # dynamic assignment of all numbers mentioned in the range;
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
### *!important*

In [18]:
# my solution
ans = np.random.random((5, 5))
ans[0], ans[-1] = 0, 0
ans[:, 0:1], ans[:, -1] = 0, 0
ans

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.97097511, 0.87940971, 0.25512795, 0.        ],
       [0.        , 0.12434083, 0.72442612, 0.73694358, 0.        ],
       [0.        , 0.53525592, 0.20821638, 0.44499224, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [19]:
# ALternate indexing
ans = np.random.random((5, 5))
ans[:, [0, -1]], ans[[0, -1], :] = 0, 0
ans

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.81184463, 0.65157676, 0.80312656, 0.        ],
       [0.        , 0.5432154 , 0.20396299, 0.39071607, 0.        ],
       [0.        , 0.0476604 , 0.69679084, 0.31000093, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [20]:
# Author's Solution
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

### *!important*

In [21]:
np.nan

nan

In [22]:
np.inf

inf

In [23]:
0.3

0.3

In [24]:
3 * 0.1

0.30000000000000004

In [25]:
0.6-0.2

0.39999999999999997

In [26]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

### *!important*

Signature: np.diag(v, k=0)
Docstring:
Extract a diagonal or construct a diagonal array.

- See the more detailed documentation for ``numpy.diagonal`` if you use this function to extract a diagonal and wish to write to the resulting array; whether it returns a copy or a view depends on what version of numpy youare using.

#### Parameters
----------
- v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
- k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

#### Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

#### See Also
--------
- diagonal : Return specified diagonals.
- diagflat : Create a 2-D array with the flattened input as a diagonal.
- trace : Sum along diagonals.
- **triu : Upper triangle of an array.**
- **tril : Lower triangle of an array.**

#### Examples
--------
```python
>>> x = np.arange(9).reshape((3,3))
>>> x
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

>>> np.diag(x)
array([0, 4, 8])
>>> np.diag(x, k=1)
array([1, 5])
>>> np.diag(x, k=-1)
array([3, 7])

>>> np.diag(np.diag(x))
array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])
```

In [27]:
d = np.random.rand(5, 5)
print(d)
np.diag(d)

[[0.79389323 0.64872082 0.20493202 0.30314588 0.53219584]
 [0.69358677 0.73523737 0.76080313 0.28675475 0.41865917]
 [0.68641346 0.22529669 0.27809402 0.0810512  0.16650082]
 [0.02521234 0.73878261 0.98776653 0.14324347 0.4472534 ]
 [0.33422111 0.8900532  0.82885452 0.89677254 0.7998618 ]]


array([0.79389323, 0.73523737, 0.27809402, 0.14324347, 0.7998618 ])

In [28]:
np.diag(np.arange(1, 5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [29]:
np.diag(np.arange(1, 5), k = 2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
&#x2611;

In [30]:
ans = np.zeros((8, 8))
ans[::2, ::2] = 1
ans[1::2, 1::2] = 1
ans

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [31]:
# AUthor's Solution
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
&#x2612;
#### !important

In [35]:
# naive approach;
a = np.random.random((6, 7, 8))
ans = np.where(a == a.reshape(-1)[99])   # important
ans

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

In [43]:
for item in ans:
    print(item[0], end = " ")

1 5 3 

In [33]:
# Author's Solution
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
&#x2612;
[REFERENCE](https://www.w3resource.com/numpy/manipulation/tile.php?passed=passed)

In [56]:
np.tile([0, 1], 4)

array([0, 1, 0, 1, 0, 1, 0, 1])

In [57]:
np.tile([0, 1], (8, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)
&#x2612;
### !important

- Normalization usually means to scale a variable to have a values between 0 and 1, 
- while standardization transforms data to have a mean of zero and a standard deviation of 1. 
- This standardization is called a z-score, and data points can be standardized with the following formula: A z-score standardizes variables.
    - [REFERENCE](https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-7.php?passed=passed)

In [58]:
arr = np.random.random((5, 5))
print("Original Array:")
arr

Original Array:


array([[0.8307355 , 0.01314454, 0.24036393, 0.14989266, 0.95150477],
       [0.79740699, 0.51140719, 0.21527185, 0.88599032, 0.91105842],
       [0.00974626, 0.40138139, 0.77401711, 0.48406852, 0.78057614],
       [0.70775628, 0.32662421, 0.84257031, 0.62733096, 0.03362962],
       [0.9911991 , 0.88346984, 0.00820325, 0.42794097, 0.03594726]])

In [60]:
print("After normalization:")
mn, mx = arr.min(), arr.max()
arr = (arr - mn) / (mx - mn)
arr

After normalization:


array([[0.83676065, 0.00502677, 0.23617666, 0.1441404 , 0.95961902],
       [0.80285561, 0.5119085 , 0.21065053, 0.89297128, 0.91847302],
       [0.0015697 , 0.39997945, 0.77906113, 0.48409692, 0.78573362],
       [0.7116541 , 0.3239291 , 0.84880018, 0.62983756, 0.0258662 ],
       [1.        , 0.89040721, 0.        , 0.42699847, 0.02822393]])

In [61]:
# Author's Solution:
# (x - mean) / std

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.05102296  0.88579578  1.40850427  0.98285152 -0.13914972]
 [-0.90538341  0.04352886 -0.93551644  0.67459041 -1.70145171]
 [-1.83822684 -0.96561745  1.24847392  1.19761123 -1.48006523]
 [-0.3497828  -0.59795329  0.9050159   0.04757093  1.15698048]
 [ 0.31806384 -0.21427489  0.2818362  -1.4215098   1.34708527]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
&#x2612;

In [72]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Tushar Nankani\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
&#x2611;

In [73]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
c = a @ b
d = np.dot(a, b)
e = np.matmul(a, b)
print(a, b, c, d, e, sep = "\n\n")

[[0.29025806 0.20393386 0.90045218]
 [0.1252596  0.01470228 0.17997892]
 [0.23371103 0.88390326 0.16393036]
 [0.02997314 0.17943212 0.98018413]
 [0.91930251 0.96576359 0.72782687]]

[[0.7541163  0.99159572]
 [0.40729372 0.83095865]
 [0.99490097 0.90545137]]

[[1.19781006 1.27259492]
 [0.27950966 0.29938604]
 [0.69934801 1.11466489]
 [1.07087095 1.06633097]
 [1.8107261  2.37309789]]

[[1.19781006 1.27259492]
 [0.27950966 0.29938604]
 [0.69934801 1.11466489]
 [1.07087095 1.06633097]
 [1.8107261  2.37309789]]

[[1.19781006 1.27259492]
 [0.27950966 0.29938604]
 [0.69934801 1.11466489]
 [1.07087095 1.06633097]
 [1.8107261  2.37309789]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
&#x2611;

In [83]:
arr = np.random.rand(10)
print(arr)
arr[4:8] *= -1
print(arr)

[0.13278881 0.82479588 0.21125426 0.12869001 0.50834072 0.80369119
 0.39478851 0.08679078 0.36725697 0.97253669]
[ 0.13278881  0.82479588  0.21125426  0.12869001 -0.50834072 -0.80369119
 -0.39478851 -0.08679078  0.36725697  0.97253669]


In [84]:
# Author's Solution

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
&#x2612;
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

- My Answer
    - 9
    - 9
- Correct Answer
    - 9
    - 10
    
### Reason:
- Numpy must be redefining range, and it has different boundry rules. 
- The first line is equivalent to 0+1+2+3+4+(-1). 
- The third line is equivalent to 0+1+2+3+4 on axis=-1. 
    - Use import numpy as np and then rewrite the third line as np.sum(range(5),-1).
- Numpy does not redefine range. The second argument in np.sum() is `axis`. It will only sum the items in the first argument.
    - [SOURCE](https://stackoverflow.com/questions/42955201/python-numpy-range-and-sum-1)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
~ Some still unclear
&#x2612;
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- MY ANSWERS:
    - NO
    - NO
    - YES
    - NO
    - YES
    - YES

In [92]:
2 << Z

array([   2,    4,    8,   16,    0,    0,    0,    0,  512, 1024, 2048],
      dtype=int32)

In [94]:
2 << Z >> 2

array([  0,   1,   2,   4,   0,   0,   0,   0, 128, 256, 512], dtype=int32)

In [96]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j,  0. +8.j,  0. +9.j,  0.+10.j])

In [97]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10.])

- CORRECT ANSWERS
    - NO
    - YES
    - YES
    - YES
    - YES
    - NO

#### 28. What are the result of the following expressions?
### !important
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [107]:
np.array(0) / np.array(0)

C:\Users\Tushar Nankani\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [108]:
np.array(0) // np.array(0)

C:\Users\Tushar Nankani\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [109]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)
&#x2612;

In [122]:
Z = np.random.uniform(-10,+10,10)
print(Z)

print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 2.43049184  9.61227789 -3.61897373 -4.97119004  8.28950218  1.49072984
  6.32924551 -4.33735997 -9.0168307   8.9999599 ]
[  3.  10.  -4.  -5.   9.   2.   7.  -5. -10.   9.]
[  3.  10.  -4.  -5.   9.   2.   7.  -5. -10.   9.]


#### 30. How to find common values between two arrays? (★☆☆)
&#x2612;

In [125]:
# Author's Solution

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 4 6 9]


In [126]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
##### !important
&#x2612;

In [127]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [128]:
# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100